# .travis.yml
# vim: ai et ts=4 sw=4 sts=4 ft=yaml fileencoding=UTF-8
---
sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox
