# Config file for automatic testing at travis-ci.org
# vim: ai et ts=2 sw=2 sts=2 ft=yaml fenc=UTF-8

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script: python setup.py test
